Launch kpi_forecast tasks in derived-datasets
Since the airflow upgrade in
https://github.com/mozilla/telemetry-airflow/pull/1377
these tasks are failing with:

> ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=403, message=Required "container.clusters.get" permission(s) for "projects/moz-fx-data-shared-prod/zones/us-central1-a/clusters/bq-load-gke-1"

These tasks should be writing to shared-prod, but accessing the GKE cluster
using the default connection and project.