Burnham python3 fix
Recent runs have failed with:

> TypeError: Object of type bytes is not JSON serializable

Which I believe is directly related to the switch to running WTMO on python3.